### ISSUE TITLE
MessageFormat parse panic

### ISSUE THREAD

**Issue by VladislavsPerkanuks** [translate-agent/translate#159]
When parsing translated Supersets file one of the messages contains a `+` character which breaks parse.

Test case for reproduction
`pkg/messageformat/parse_test.go Test_Parse()`
```go
{
  name:     "...",
  input:    "{+ vēl %s}",
  expected: ...,
},
```

stack
```go
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 15 [running]:
testing.tRunner.func1.2({0x1028d9bc0, 0x1400022a000})
	/Users/vladislavs/.gobrew/current/go/src/testing/testing.go:1545 +0x1c8
testing.tRunner.func1()
	/Users/vladislavs/.gobrew/current/go/src/testing/testing.go:1548 +0x360
panic({0x1028d9bc0?, 0x1400022a000?})
	/Users/vladislavs/.gobrew/current/go/src/runtime/panic.go:914 +0x218
go.expect.digital/translate/pkg/messageformat.(*parser).nextToken(...)
	/Users/vladislavs/Projects/translate/pkg/messageformat/parse.go:244
go.expect.digital/translate/pkg/messageformat.(*parser).parseText(0x14000196e90)
	/Users/vladislavs/Projects/translate/pkg/messageformat/parse.go:90 +0x5d0
go.expect.digital/translate/pkg/messageformat.(*parser).parse(0x14000221e90)
	/Users/vladislavs/Projects/translate/pkg/messageformat/parse.go:66 +0x230
go.expect.digital/translate/pkg/messageformat.Parse({0x10282cef8, 0xb})
	/Users/vladislavs/Projects/translate/pkg/messageformat/parse.go:39 +0xdc
go.expect.digital/translate/pkg/messageformat.Test_Parse.func1(0x0?)
	/Users/vladislavs/Projects/translate/pkg/messageformat/parse_test.go:136 +0x3c
testing.tRunner(0x1400018b860, 0x1400002a3c0)
	/Users/vladislavs/.gobrew/current/go/src/testing/testing.go:1595 +0xe8
created by testing.(*T).Run in goroutine 20
	/Users/vladislavs/.gobrew/current/go/src/testing/testing.go:1648 +0x33c
```

When parsing `+`, it gets token type `tokenTypeError`, which is allegadly cause of the panic

**Comment by VladislavsPerkanuks** [comment]
Yeah, it tries to parse as an opening to function and fails 
```go
case '+':
  return lexOpeningFunction(l)

func lexOpeningFunction(l *lexer) stateFn {
	first := l.next()

	if !isNameFirstChar(first) { // <--- error here
		return l.emitToken(mkTokenErrorf(`invalid first character in function name %v at %d`, first, l.pos))
	}
```

**Comment by DarjaLeonova** [comment]
It was done in this PR.
https://github.com/translate-agent/translate/pull/164
